-- A lexical scanner generated by aflex
with text_io; use text_io;
with prop_lexer_dfa; use prop_lexer_dfa; 
with prop_lexer_io; use prop_lexer_io; 
--# line 1 "prop_lexer.l"
--# line 8 "prop_lexer.l"



with
  Ada.Strings.Unbounded,
  Prop_Parser_Tokens,
  Prop,
  Utils.Strings;

use
  Ada.Strings.Unbounded, 
  Prop_Parser_Tokens,
  Prop,
  Utils.Strings;

package Prop_Lexer is

   function Yylex return Token;

   function get_line_number return natural;

   function get_column_number return natural;

   function get_token_value return Unbounded_String;

   procedure initialize_lexer
     (file_name : in Unbounded_String);

   procedure finalize_lexer;

   procedure raise_lexer_exception
     (err : in string);

   function Get_Error_Msg return Unbounded_String;

   lexical_exception : exception;

private


   file_name : Unbounded_String;
   Error_Msg : Unbounded_String;

end Prop_Lexer;
