#!/bin/bash

MAX=$1

outDir=out/dbfs

[ "$MAX"  = "" ] && echo "missing \$1 = MAX # of nodes" && exit 1
[ ! -d $outDir ] && echo "$outDir does not exist" && exit 1

lp=1
echo -n > plot

ls -1 $outDir/*xml | \
    awk -F'_N' '{print $1}' | \
    awk -F'/' '{print $NF}' | \
    sort -u | \
    while read m
    do
        echo $m
	echo -n "reset; set terminal png size 600, 600;
set yrange [0:];
set output \"time-dbfs-$m.png\";
set title \"Temps d'execution pour ${m//_/\\\\_}\"
set xtics 1;" >> plot
	no=1
	plotCmd="plot "
        for P in 1 2 4 8
        do
            dat=$outDir/$m-$P.dat
            echo -n > $dat
            for N in $(seq 1 $MAX)
            do
		f=$outDir/$m"_N"$N"_P"$P".xml"
		[ ! -f "$f" ] && continue
		l=$(scripts/get-stat $f searchTime)
		resTime=$(scripts/list-op min $l)
		echo "$N $resTime" >> $dat
		if [ $P -gt 1 ]
		then
		    eval "ref=\$ref_$N"
		    ratio=$(echo "scale = 2 ; $ref / $resTime" | bc)
		    echo "set label \"$ratio\" at $N,$resTime+1;" >> plot
		else
		    eval "ref_$N=$resTime"
		fi
            done
	    if [ $no != 1 ]
	    then
		plotCmd=$plotCmd", " >> plot
	    fi
	    plotCmd=$plotCmd"\"$dat\" with lp ls $no title \"$P proc./noeud\""
	    no=$((no + 1))
	done
	echo $plotCmd ";" >> plot
	cat plot | gnuplot
	rm plot
    done
