#!/bin/bash

MAXW=8

export PATH=$HOME/helena/bin:$PATH

if [ -z "$OAR_NODEFILE" ]
then
    for N in $(seq 1 $MAXW)
    do
	echo localhost
    done > machinefile
else
    cat $OAR_NODEFILE | sort -u \
	| while read host
    do
	echo "$host max-slots=1"
    done > machinefile
fi
cat machinefile

minStates=10000000
maxStates=100000000
outDir=out/ddfs
mkdir -p $outDir &> /dev/null
scripts/select-models $minStates $maxStates \
    | while read m lang st opt
      do
	  echo $m - $st states
	  hashSize=21
	  size=1048576
	  while [ $size -lt $st -a $hashSize != 30 ]
	  do
	      hashSize=$((hashSize + 1))
	      size=$((size * 2))
	  done
	  f=$(scripts/get-file $m $lang)
	  param=$(scripts/format-parameters $opt)
	  for N in $(seq 2 $MAXW)
	  do
	      xml=$outDir/$m
	      if [ "$opt" != "" ]
	      then
		  xml=$xml-$(echo $opt | tr " " "-")
	      fi
	      xml=$xml-$N.xml
	      if [ ! -e $xml ]
	      then
		  cmd="helena --hash-size=$hashSize "$param
		  if [ $N -gt 1 ]
		  then
		      head -$N machinefile > mf
                      cat mf
		      cmd=$cmd" --algo=ddfs --machine-file=mf"
		  else
		      cmd=$cmd" --algo=dfs"
		  fi
		  cmd=$cmd" --progress=no-report --report-file="$xml" $f"
		  echo $cmd
                  eval $cmd &> /dev/null
	      fi
	  done
      done
