#!/bin/bash

[ -z "$OAR_NODEFILE" ] && echo "not in an OAR job" && exit 1
[ -z "$1" ] && echo "missing \#1 = comp. size range" && exit 1

range=$1

C5="collision.5;12;27;27"
FT6="firewire_tree.6;8;26;26"
FT7="firewire_tree.7;8;26;26"
LE6="leader_election.6;12;26;26"
LE7="leader_election.7;12;26;26"
L9="lifts.9;16;26;26"
S9="synapse.9;18;28;27"

MODELS="$C5 $FT6 $FT7 $LE6 $LE7 $L9 $S9"

SINGLE_BUFFER_SIZES="64000" # 128000" # 256000"

NODES=$(seq 32 -4 8)

PROCS_PER_NODE="4 2 1"
PROCS_PER_NODE="4"

REPETITION=2

COMP_MODES="C DC"

mf=machinefile-$OAR_JOBID
helena="helena -g=no-report -A=DBFS -N=EXPLORE -mf=$mf -ccs=$range"
outDir=out/dist-compression/$range

mkdir -p $outDir &> /dev/null
for n in $NODES
do
    for p in $PROCS_PER_NODE
    do
	sort -u $OAR_NODEFILE | head -$n > $mf
	[ $(cat $mf | wc -l) -lt $n ] && \
	    echo "not enough nodes for n=$n" && continue
	for mcbt in $MODELS
	do
	    m=$(echo $mcbt | cut -d";" -f1)
	    cb=$(echo $mcbt | cut -d";" -f2)
            tc=$(echo $mcbt | cut -d";" -f3)
            tnc=$(echo $mcbt | cut -d";" -f4)
	    dve="../examples/beem/$m.dve"
	    for b in $SINGLE_BUFFER_SIZES
	    do
		bs=$(((n * p - 1) * $b))
		[ $bs -gt 100000000 ] && continue
		for c in $COMP_MODES
		do
                    if [ "$c" = "NC" ]
                    then
                        t=$tnc
                        dir=$outDir/$m/$n/$p/NC/$b
                        copt=""
                    else
                        t=$tc
                        copt="-$c"
                    fi
                    q=$p
                    while [ $q -gt 1 ]
                    do
                        t=$((t - 1))
                        q=$((q / 2))
                    done
                    baseCmd="$helena -np=$p -t=$t -cb=$cb"
                    dir=$outDir/$m/$n/$p/$c/$b
                    mkdir -p $dir &> /dev/null
		    for r in $(seq -w 1 $REPETITION)
		    do
			xml=$dir/$r.xml
                        out=$dir/$r.out
                        while [ ! -e $xml ]
                        do
                            echo "***** $m, $n nodes, $p procs, b=$b, m=$c *****"
			    cmd="$baseCmd $copt -o=$xml -bs=$bs $dve"
			    echo $cmd
			    eval $cmd | tee $out
                        done
		    done
		done
	    done
	done
	rm $mf
    done
done

exit 0
