#!/usr/bin/python

import os
import sys
import test_gen

inDir = "../examples/beem/"
dveLtlModels = []
for(_, _, files) in os.walk(inDir):
    for f in files:
        (f, ext) = os.path.splitext(f)
        if ext == ".dve":
            (_, ext2) = os.path.splitext(f)
            m = os.path.abspath(inDir + os.sep + f + ext)
            if ext2[1:5] == "prop":
                dveLtlModels.append(m)

cmd = "helena"
opts = [
    ["-tr=events"],
    ["-N=check"],
    ["-o=report.xml"],
    ["-t=26"],
    ["-tl=120"],
    ["-A=dfs"],
    ["-W=1"],
    ["-S=0"],
    ["-H=0"],
    dveLtlModels
]
post = "mv report.xml %d"
    
t = test_gen.Test(cmd, options = opts, postCmd = post)
generator = test_gen.TestScriptGenerator()
generator.addTest(t)
generator.genScript()
exit(0)
